ALTER TABLE events ADD COLUMN IF NOT EXISTS price INTEGER DEFAULT 0;
ALTER TABLE events ADD COLUMN IF NOT EXISTS data TEXT DEFAULT '';

ALTER TABLE colectivos ADD COLUMN IF NOT EXISTS vtv TIMESTAMP DEFAULT '2000-01-01 00:00:00';
